name: EPG Mirror Updater

on:
  schedule:
    - cron: '0 */3 * * *'  # Every 3 hours
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download EPG XML
        run: |
          curl -L -o epg.xml https://opop.pro/6w4j4x3jpYcG

      - name: Commit and push EPG
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add epg.xml
          git commit -m "Update EPG [skip ci]" || echo "No changes to commit"
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
